### ISSUE TITLE
Feature request: headphone jack detect

### ISSUE THREAD

**Issue by haklein** [sparkfun/SparkFun_WM8960_Arduino_Library#8]
The library is amazing, thanks for that. I'd require enabled headphone jack detection. Detection does work fine for me via LINPUT3 and those bits being set:
~~~
       codec._writeRegisterBit(WM8960_REG_ADDITIONAL_CONTROL_2, 6, 1); // HPSWEN
       codec._writeRegisterBit(WM8960_REG_ADDITIONAL_CONTROL_4, 3, 1); // HPSEL to JD2 (LINPUT3)
       codec._writeRegisterBit(WM8960_REG_ADDITIONAL_CONTROL_1, 0, 1); // TOEN - slow clock enable 
~~~
It's just that  `_writeRegisterBit()` is private, same for the local register copy. So I don't see a "public" way to set just those bits in the current library version.

**Comment by lewispg228** [comment]
Hi @haklein ,
Thanks for this suggestion. Increasing support for jack detection would be great! 

Usually, in our Arduino libraries, we keep lower level functions like `_writeRegisterBit()` private. In order to use it, we usually create a public function that calls it. As an example, see [enableVREF()](https://github.com/sparkfun/SparkFun_WM8960_Arduino_Library/blob/main/src/SparkFun_WM8960_Arduino_Library.cpp#L158). This can make the Arduino Sketch a bit more human-readable and approachable for new coders.

I would suggest creating new public functions called `enableJackDetection()` and `disableJackDetection().` And perhaps there are some other detection settings that could be set with more specific functions and/or arguments.

Would you be willing to give this a try and submit a pull request with your changes?

Let us know and thanks,
Pete

**Comment by haklein** [comment]
Hi Pete, sure. I'll add a method to enable/disable detection as above and a method to set the detection pin (LINPUT3, RINPUT3 and GPIO are the possible options so will add an enum for those). PR will follow.
thx and br, Hari

**Comment by lewispg228** [comment]
Looks great. Thanks for your pull request!

I went ahead and added in an example (16) to demonstrate setting this up. I was able to verify with my setup manually changing the jack detect pin (LINPUT3), but unfortunately, I don't have the correct 1/4"-to-3.5mm adapter handy to verify with inserting a cable. Either way, it is reacting properly to HIGH/LOW signals. Thanks again @haklein !!
